version: "4.3"

services:
    inlEdgeDashboard-app:
        build:
            context: "."
        container_name: inlEdgeDashboard-app
        ports:
            - 8091:8481
        networks:
            backend:
                aliases:
                    - app

networks:
    backend:
        name: inlEdgeDashboard-network
