version: "4.3"

services:
    fe_dashboardinl-app:
        build:
            context: "."
        container_name: fe_dashboardinl-app
        ports:
            - 8481:8481
        networks:
            backend:
                aliases:
                    - app

networks:
    backend:
        name: fe_dashboardinl-network
